# Generated by Django 5.2.6 on 2025-10-14 04:50

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15, unique=True)),
                ('student_class', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.student_image_path)),
                ('token_number', models.AutoField(primary_key=True, serialize=False)),
                ('cr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cr')),
            ],
        ),
    ]
